Create Chinese (Simplified) translation
FaeCraft/Flamingo pull request #5
Opened 2020-10-30 03:41 UTC by linzexin022

2020-11-09 22:56 UTC, gdude2002 commented
Sorry for taking so long to get back to you. Thanks for your pull request!

I'll review this and merge it when I get a chance — I think these translations are good, though.

2020-11-09 23:21 UTC, LeoCTH requested changes

2020-11-09 23:21 UTC, LeoCTH commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "item.flamingo_ooo.shrimp_cocktail": "鲜虾盅",
urm... shrimp cocktail is a dish duh

2020-11-09 23:21 UTC, LeoCTH commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "item.flamingo_ooo.cooked_shrimp": "煮熟的虾",
煮熟的虾 -> 熟虾仁?

2020-11-09 23:21 UTC, LeoCTH commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "item.flamingo_ooo.shrimp_cocktail": "鲜虾盅",
~~also the shrimp in a shrimp cocktail is *cooked* smh~~

2020-11-09 23:21 UTC, LeoCTH commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "effect.flamingo_ooo.shrimp": "火烈鸟视觉",
......what?

2020-11-10 05:55 UTC, linzexin022 commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "item.flamingo_ooo.shrimp_cocktail": "鲜虾盅",
Thank you for your advice. I think it's an appetizer in western food that contains cooked shrimps and hot sauce. However, since the recipe is three cooked shrimps and a bowl, and from the perspective of Chinese dishes, there exists a dish called "鲜虾盅" which is cooked with fresh shrimps and held by a small soup cup. “鲜虾” doesn't refer to raw shrimp, but to distinguish with dried shrimp. So I think it's OK to translate it to "鲜虾盅"

2020-11-10 05:59 UTC, linzexin022 commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "item.flamingo_ooo.cooked_shrimp": "煮熟的虾",
Thank you for your advice. Your suggestion is more simple, straightforward and easy to understand. I'll correct it.

2020-11-10 06:19 UTC, linzexin022 commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "effect.flamingo_ooo.shrimp": "火烈鸟视觉",
Thank you again for your query. I do not know what "Flamingo'd" actually refers to, so I translated it to "火烈鸟视觉". After my second confirm, I think my translation is wrong. The logo of this effect is shrimp, so it may refer to the visual effect of shrimp which will make you see with a pink mask. I'll correct it to "虾的视觉" temporary until the author explains what it really refers to.

2020-11-10 10:54 UTC, gdude2002 commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "effect.flamingo_ooo.shrimp": "火烈鸟视觉",
"Flamingo Vision" is actually fine for this one, on balance — that's what the `zh_tw` translation calls it as well.

2020-11-10 10:59 UTC, Neubulae requested changes

2020-11-10 10:59 UTC, Neubulae commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "subtitle.flamingo.ambient": "咯（火烈鸟叫声）",
To make it more compliant to Vanilla standard: make it 火烈鸟：咯

2020-11-10 10:59 UTC, Neubulae commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "subtitle.flamingo.baby.ambient": "叽啾（小火烈鸟叫声）"
…and 小火烈鸟：叽啾 too

2020-11-10 10:59 UTC, Neubulae commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "item.flamingo_ooo.shrimp_cocktail": "鲜虾盅",
How about 鸡尾酒鲜虾? 鸡尾酒虾 is a common translation afterall.

2020-11-10 10:59 UTC, Neubulae commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "item.flamingo_ooo.suspicious_chicken": "生禽肉",
"生鸡肉…？" could work maybe. Tho it would be too suspicious(no pun intended)

2020-11-10 12:49 UTC, linzexin022 commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "effect.flamingo_ooo.shrimp": "火烈鸟视觉",
OK, I'll take the previous one.

2020-11-10 12:51 UTC, linzexin022 commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "subtitle.flamingo.ambient": "咯（火烈鸟叫声）",
Thank you for your advice. Your suggestion has been approved.

2020-11-10 12:51 UTC, linzexin022 commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "subtitle.flamingo.baby.ambient": "叽啾（小火烈鸟叫声）"
Thank you for your advice. Your suggestion has been approved.

2020-11-10 13:02 UTC, linzexin022 commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "item.flamingo_ooo.suspicious_chicken": "生禽肉",
Nice suggestion

2020-11-10 13:09 UTC, linzexin022 commented on src/main/resources/assets/flamingo_ooo/lang/zh_cn.json
> +  "item.flamingo_ooo.shrimp_cocktail": "鲜虾盅",
You're right, I'll take "鸡尾酒虾" instead

2020-11-18 15:46 UTC, closed without merging

2020-11-18 19:05 UTC, gdude2002 commented
Whoops, I did not mean to close this prematurely. I'll see about getting it put into the new branch when I can.