Improve german translation
FaeCraft/Flamingo pull request #9
Opened 2021-05-12 15:51 UTC by koelle25

Hi,

I changed the german translations a bit to more closely match the original german translations for similar items.
Hope you appreciate it!

2021-05-12 19:16 UTC, Scotsguy requested changes

2021-05-12 19:16 UTC, Scotsguy commented on src/main/resources/assets/flamingo_ooo/lang/de_de.json
> +  "item.flamingo_ooo.flamingo_egg": "Flamingo-Ei",
`minecraft:turtle_egg` ist Schildkrötenei auf Deutsch, Flamingoei ist also konsistenter

```suggestion
  "item.flamingo_ooo.flamingo_egg": "Flamingoei",
```

2021-05-13 10:42 UTC, Scotsguy approved these changes

2021-05-13 11:54 UTC, gdude2002 commented
Thanks for your contribution!

2021-05-13 11:54 UTC, merged